Repository DogCatWorldTeam/frontend, pull requests merged in 2024-06, with the labels that each got.

#45 feat: axios 설치 및 회원가입 api 연동
  abandonedpets/package.json
  abandonedpets/src/components/NavBar.tsx
  abandonedpets/src/components/signup/RegisterForm.tsx
  abandonedpets/yarn.lock
Labels: Feat

#47 [feat] 로그인 api 연동
  abandonedpets/package.json
  abandonedpets/src/App.tsx
  abandonedpets/src/auth/TokenRefresher.tsx
  abandonedpets/src/components/NavBar.tsx
  abandonedpets/src/components/login/LoginForm.tsx
  abandonedpets/src/components/signup/RegisterForm.tsx
  abandonedpets/yarn.lock
Labels: Feat

#51 design: 입양/분양 페이지 api 연동
  abandonedpets/src/App.tsx
  abandonedpets/src/components/petDetail/DetailText.tsx
  abandonedpets/src/components/petDetail/Info.tsx
  abandonedpets/src/components/petWrite/Form.tsx
  abandonedpets/src/components/pets/CatList.tsx
  abandonedpets/src/components/pets/DogList.tsx
  abandonedpets/src/components/pets/PetCard.tsx
  abandonedpets/src/components/pets/SelectPage.tsx
Labels: Feat, design

#52 [feat] 보호소 전체 조회 api 연동
  abandonedpets/src/components/shelter/ShelterList.tsx
  abandonedpets/src/main.tsx
Labels: Feat

#54 design: api 연결된 부분 세부 디자인 수정
  abandonedpets/index.html
  abandonedpets/src/components/petDetail/DetailText.tsx
  abandonedpets/src/components/petDetail/Info.tsx
  abandonedpets/src/components/petWrite/Form.tsx
  abandonedpets/src/components/pets/CatList.tsx
  abandonedpets/src/components/pets/DogList.tsx
  abandonedpets/src/components/pets/PetCard.tsx
  abandonedpets/src/components/pets/SelectPage.tsx
  abandonedpets/src/pages/Cat.tsx
  abandonedpets/src/pages/Dog.tsx
Labels: design

#58 feat: 보호소 클릭 시 유기동물 데이터 연결
  abandonedpets/src/components/shelter/SelectPage.tsx
  abandonedpets/src/components/shelter/ShelterList.tsx
Labels: Feat

#60 design: navbar 및 doglist 페이지 반응형 적용
  abandonedpets/src/App.css
  abandonedpets/src/components/NavBar.tsx
  abandonedpets/src/components/pets/DogList.tsx
  abandonedpets/src/components/pets/PetCard.tsx
  abandonedpets/src/components/pets/Search.tsx
Labels: design

#62 feat: 로그인시 userId localstorage에 저장 및 삭제
  abandonedpets/src/components/NavBar.tsx
  abandonedpets/src/components/login/LoginForm.tsx
Labels: Feat

#65 Feat: 게시글 작성 데이터 수정
  abandonedpets/src/auth/TokenRefresher.tsx
  abandonedpets/src/components/NavBar.tsx
  abandonedpets/src/components/login/LoginForm.tsx
  abandonedpets/src/components/petWrite/Form.tsx
  abandonedpets/src/components/pets/Search.tsx
  abandonedpets/src/pages/PetDetail.tsx
Labels: Feat

#70 feat: 채팅 기능 구현 완료
  abandonedpets/src/components/NavBar.tsx
  abandonedpets/src/components/chat/Input.tsx
  abandonedpets/src/components/chat/ListItem.tsx
  abandonedpets/src/components/chat/Messges.tsx
  abandonedpets/src/components/modal/Chat.tsx
  abandonedpets/src/components/modal/ChatList.tsx
  abandonedpets/src/components/petDetail/Info.tsx
  abandonedpets/src/components/petDetail/SendMessageBtn.tsx
  abandonedpets/src/pages/PetDetail.tsx
Labels: Feat

#75 fix: yarn build
  abandonedpets/src/App.tsx
  abandonedpets/src/auth/TokenRefresher.tsx
  abandonedpets/src/components/NavBar.tsx
  abandonedpets/src/components/chat/InfoBar.tsx
  abandonedpets/src/components/chat/Input.tsx
  abandonedpets/src/components/chat/ListItem.tsx
  abandonedpets/src/components/chat/Messges.tsx
  abandonedpets/src/components/funeral/FuneralList.tsx
  abandonedpets/src/components/modal/Chat.tsx
  abandonedpets/src/components/modal/ChatList.tsx
  abandonedpets/src/components/mypage/FavoriteList.tsx
  abandonedpets/src/components/mypage/MyPageList.tsx
  abandonedpets/src/components/petDetail/DetailText.tsx
  abandonedpets/src/components/petDetail/Info.tsx
  abandonedpets/src/components/petDetail/SendMessageBtn.tsx
  abandonedpets/src/components/petWrite/Form.tsx
  abandonedpets/src/components/pets/CatList.tsx
  abandonedpets/src/components/pets/DogList.tsx
  abandonedpets/src/components/pets/PetCard.tsx
  abandonedpets/src/components/shelter/ShelterList.tsx
  abandonedpets/src/main.tsx
  abandonedpets/src/pages/LoginPage.tsx
  abandonedpets/src/pages/PetDetail.tsx
  abandonedpets/src/pages/ShelterPage.tsx
  abandonedpets/src/pages/SignUpPage.tsx
Labels: Fix, Feat, design

#77 [feat] 검색 api 연동
  abandonedpets/.gitignore
  abandonedpets/src/components/funeral/FuneralList.tsx
  abandonedpets/src/components/login/LoginForm.tsx
  abandonedpets/src/components/mypage/MyPageList.tsx
  abandonedpets/src/components/petDetail/Info.tsx
  abandonedpets/src/components/petDetail/SendMessageBtn.tsx
  abandonedpets/src/components/petWrite/Form.tsx
  abandonedpets/src/components/pets/CatList.tsx
  abandonedpets/src/components/pets/DogList.tsx
  abandonedpets/src/components/pets/PetCard.tsx
  abandonedpets/src/components/pets/Search.tsx
  abandonedpets/src/components/shelter/ShelterList.tsx
  abandonedpets/src/components/signup/RegisterForm.tsx
  abandonedpets/src/pages/Cat.tsx
  abandonedpets/src/pages/Dog.tsx
  abandonedpets/src/pages/FuneralPage.tsx
  abandonedpets/src/pages/PetDetail.tsx
  abandonedpets/src/vite-env.d.ts
Labels: Fix, Feat

#81 fix: 콘솔 경고 메세지 오류 수정
  abandonedpets/src/components/NavBar.tsx
  abandonedpets/src/components/modal/Chat.tsx
  abandonedpets/src/components/pets/DogList.tsx
  abandonedpets/src/components/pets/PetCard.tsx
Labels: Fix

#83 [fix] 에러 및 디자인 개선
  abandonedpets/Dockerfile
  abandonedpets/src/auth/TokenRefresher.tsx
  abandonedpets/src/components/NavBar.tsx
  abandonedpets/src/components/chat/Messges.tsx
  abandonedpets/src/components/modal/Chat.tsx
  abandonedpets/src/components/petWrite/Form.tsx
  abandonedpets/src/components/pets/CatList.tsx
  abandonedpets/src/components/pets/DogList.tsx
  abandonedpets/src/components/pets/Search.tsx
  abandonedpets/vite.config.ts
Labels: Fix, Docs, design
